main: live.btaure.bieliauskutaure2.BieliauskuTaure2
version: 1.0
name: 'MCBieliauskuTaure2'
api-version: '1.19'
commands:
  team:
    description: Can be used to modify and add teams
    usage: as neisivaizduoju
  minigame:
    description: Interacts with the MinigameManager
    usage: The command failed. /minigame <task> <args>
  test:
    description: xd?
  debuglevel:
    description: Sets debug level 1-4.
    usage: /debuglevel <skaicius(1-4)>
  setrole:
    description: Sets a role for a specific player.
    usage: /setrole <zaidejo vardas> <role>
