main: live.btaure.bieliauskutaure2.BieliauskuTaure2
version: 1.0
name: 'MCBieliauskuTaure2'
api-version: '1.16'
commands:
  team:
    description: Can be used to modify and add teams
    usage: as neisivaizduoju
  minigame:
    description: Interacts with the MinigameManager
    usage: The command failed. /minigame <task> <args>
  test:
    description: xd?